# Generated by Django 4.0.5 on 2022-06-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
    ]
